server.port=9090
spring.application.name=hcn

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/hcn
spring.datasource.username=hcn
spring.datasource.password=hcn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
